apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    policies.kyverno.io/subject: Label
    policies.kyverno.io/title: Add Labels to all OpenMetadata pods
  name: add-openmetadata-labels
spec:
  background: false
  failurePolicy: Ignore
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
          - resources:
              kinds:
                - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              DataClass: Medium
      name: add-data-class-label