kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-init-scripts
  namespace: a9cb09-dev
  uid: 570be9c0-978b-401b-992c-44b3545e7203
  resourceVersion: '1062036183'
  creationTimestamp: '2024-03-07T04:12:23Z'
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: openmetadata-dependencies
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.7.2
  annotations:
    meta.helm.sh/release-name: openmetadata-dependencies
    meta.helm.sh/release-namespace: a9cb09-dev
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2024-03-07T04:12:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:init_airflow_db_scripts.sql': {}
          'f:init_openmetadata_db_scripts.sql': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:helm.sh/chart': {}
data:
  init_airflow_db_scripts.sql: >
    CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';

    GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT
    OPTION;

    commit;
  init_openmetadata_db_scripts.sql: >
    CREATE DATABASE openmetadata_db;

    CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';

    GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH
    GRANT OPTION;

    commit;