apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    policies.kyverno.io/subject: Label
    policies.kyverno.io/title: Add Labels to all OpenMetadata pods
  name: add-opensearch-labels
spec:
  background: false
  failurePolicy: Ignore
  validationFailureAction: audit
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app.kubernetes.io/name: opensearch
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            DataClass: Medium
    name: add-data-class-label