apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-ingestion-labels
spec:
  background: false
  failurePolicy: Ignore
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  task_id: ingestion_task
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              DataClass: High
      name: add-data-class-label
  validationFailureAction: audit