kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-openmetadata-profiler
spec:
  podSelector:
    matchLabels:
      task_id: profiler_task
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
status: {}
