kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-openmetadata-airflow
spec:
  podSelector:
    matchLabels:
      app: airflow
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
status: {}