kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-openmetadata
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openmetadata
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
status: {}