apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
  creationTimestamp: '2024-02-29T03:47:04Z'
  generation: 3
  managedFields:
    - apiVersion: kyverno.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:ready': {}
      manager: kyverno
      operation: Update
      subresource: status
      time: '2024-02-29T03:47:06Z'
    - apiVersion: kyverno.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:rules': {}
      manager: Mozilla
      operation: Update
      time: '2024-02-29T03:51:27Z'
  name: restrict-openmetadata-db-migration-init-container
  namespace: a9cb09-dev
  resourceVersion: '1045049951'
  uid: fbd8f559-e825-40ad-b102-bb7613f7034a
spec:
  background: true
  failurePolicy: Fail
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  app.kubernetes.io/instance: openmetadata
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: run-db-migrations
                resources:
                  limits:
                    cpu: 100m
                    memory: 500Mi
                  requests:
                    cpu: 50m
                    memory: 256Mi
  validationFailureAction: audit
status:
  conditions:
    - lastTransitionTime: '2024-02-29T03:47:06Z'
      message: ''
      reason: Succeeded
      status: 'True'
      type: Ready
  ready: true

  apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
  creationTimestamp: '2024-02-29T02:35:42Z'
  generation: 3
  managedFields:
    - apiVersion: kyverno.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:ready': {}
      manager: kyverno
      operation: Update
      subresource: status
      time: '2024-02-29T02:35:44Z'
    - apiVersion: kyverno.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:rules': {}
      manager: Mozilla
      operation: Update
      time: '2024-02-29T02:41:40Z'
  name: restrict-airflow-db-migration-init-container
  namespace: a9cb09-dev
  resourceVersion: '1044927960'
  uid: 49d0c5b5-6391-4546-97f5-4cb69f0ab6f3
spec:
  background: true
  failurePolicy: Fail
  rules:
    - exclude:
        resources:
          selector:
            matchLabels:
              component: db-migrations
      match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  app: airflow
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: wait-for-db-migrations
                resources:
                  limits:
                    cpu: 100m
                    memory: 500Mi
                  requests:
                    cpu: 50m
                    memory: 256Mi
  validationFailureAction: audit
status:
  conditions:
    - lastTransitionTime: '2024-02-29T02:35:44Z'
      message: ''
      reason: Succeeded
      status: 'True'
      type: Ready
  ready: true

apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
  creationTimestamp: '2024-02-29T02:34:33Z'
  generation: 3
  managedFields:
    - apiVersion: kyverno.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:ready': {}
      manager: kyverno
      operation: Update
      subresource: status
      time: '2024-02-29T02:34:35Z'
    - apiVersion: kyverno.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:rules': {}
      manager: Mozilla
      operation: Update
      time: '2024-02-29T02:41:31Z'
  name: restrict-airflow-check-db-init-container
  namespace: a9cb09-dev
  resourceVersion: '1044927725'
  uid: 70bad8fa-c8c3-42aa-b530-84d97774c646
spec:
  background: true
  failurePolicy: Fail
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  app: airflow
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: check-db
                resources:
                  limits:
                    cpu: 100m
                    memory: 500Mi
                  requests:
                    cpu: 50m
                    memory: 256Mi
      name: add-resource-limit
  validationFailureAction: audit
status:
  conditions:
    - lastTransitionTime: '2024-02-29T02:34:35Z'
      message: ''
      reason: Succeeded
      status: 'True'
      type: Ready
  ready: true
